version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: myapp-server
    container_name: myapp-node-server
    command: npm run start
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    env_file: ./server/.env
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: myapp-client
    container_name: myapp-react-client
    command: npm run start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    env_file: ./client/.env
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local